export const useVideoCallScenarios = () => {
  const scenarios = [
    {
      id: "job-interview",
      title: "Job Interview",
      description:
        "Practice professional interview skills and confident responses with a dedicated AI interviewer",
      difficulty: "Intermediate",
      duration: "15-20 min",
      category: "Professional",
      gradient: "from-blue-600 via-blue-700 to-indigo-800",
      imageUrl: "/images/scenarios/job-interview.jpg",
      skills: [
        "Professional Communication",
        "Confidence",
        "Interview Preparation",
        "Problem Solving",
      ],
    },
    {
      id: "coffee-shop",
      title: "Coffee Shop Conversation",
      description: "Casual conversations and everyday social interactions",
      difficulty: "Basics",
      duration: "10-15 min",
      category: "Social",
      gradient: "from-amber-500 via-orange-600 to-red-600",
      imageUrl: "/images/scenarios/coffee-shop.jpg",
      skills: ["Small Talk", "Ordering", "Social Skills"],
    },
    {
      id: "doctor-appointment",
      title: "Doctor's Appointment",
      description: "Describe symptoms and understand medical advice",
      difficulty: "Intermediate",
      duration: "15-20 min",
      category: "Healthcare",
      gradient: "from-emerald-500 via-teal-600 to-cyan-700",
      imageUrl: "/images/scenarios/doctor.jpg",
      skills: ["Medical Vocabulary", "Symptom Description", "Health"],
    },
    {
      id: "business-meeting",
      title: "Business Meeting",
      description: "Lead discussions and present ideas professionally",
      difficulty: "Advanced",
      duration: "20-25 min",
      category: "Professional",
      gradient: "from-slate-600 via-gray-700 to-zinc-800",
      imageUrl: "/images/scenarios/business-meeting.jpg",
      skills: ["Leadership", "Negotiation", "Business English"],
    },
    {
      id: "first-date",
      title: "First Date",
      description: "Build connections and express yourself naturally",
      difficulty: "Basics",
      duration: "15-20 min",
      category: "Social",
      gradient: "from-pink-500 via-rose-600 to-red-600",
      imageUrl: "/images/scenarios/first-date.jpg",
      skills: ["Personal Topics", "Getting to Know", "Romance"],
    },
    {
      id: "university-interview",
      title: "University Interview",
      description: "Showcase academic goals and personal achievements",
      difficulty: "Advanced",
      duration: "20-25 min",
      category: "Educational",
      gradient: "from-purple-600 via-violet-700 to-indigo-800",
      imageUrl: "/images/scenarios/university.jpg",
      skills: ["Academic English", "Goals", "Achievements"],
    },
    {
      id: "bank-visit",
      title: "Bank Visit",
      description: "Handle financial transactions and account inquiries",
      difficulty: "Intermediate",
      duration: "10-15 min",
      category: "Services",
      gradient: "from-green-600 via-emerald-700 to-teal-800",
      imageUrl: "/images/scenarios/bank.jpg",
      skills: ["Financial Terms", "Transactions", "Problem Solving"],
    },
    {
      id: "family-dinner",
      title: "Family Dinner",
      description: "Share stories and connect with family members",
      difficulty: "Basics",
      duration: "15-20 min",
      category: "Social",
      gradient: "from-yellow-500 via-orange-600 to-red-600",
      imageUrl: "/images/scenarios/family-dinner.jpg",
      skills: ["Family Topics", "Storytelling", "Personal Life"],
    },
    {
      id: "tech-support",
      title: "Technical Support Call",
      description: "Explain technical issues and follow troubleshooting steps",
      difficulty: "Intermediate",
      duration: "15-20 min",
      category: "Services",
      gradient: "from-blue-500 via-indigo-600 to-purple-700",
      imageUrl: "/images/scenarios/tech-support.jpg",
      skills: ["Technical Vocabulary", "Problem Description", "Instructions"],
    },
    {
      id: "networking-event",
      title: "Networking Event",
      description: "Make professional connections and exchange contacts",
      difficulty: "Advanced",
      duration: "20-25 min",
      category: "Professional",
      gradient: "from-indigo-600 via-purple-700 to-pink-800",
      imageUrl: "/images/scenarios/networking.jpg",
      skills: [
        "Professional Networking",
        "Self-Introduction",
        "Contact Exchange",
      ],
    },
    {
      id: "real-estate",
      title: "Real Estate Inquiry",
      description: "Ask about properties and negotiate rental terms",
      difficulty: "Intermediate",
      duration: "15-20 min",
      category: "Services",
      gradient: "from-teal-600 via-cyan-700 to-blue-800",
      imageUrl: "/images/scenarios/real-estate.jpg",
      skills: ["Property Description", "Negotiation", "Living Arrangements"],
    },
    {
      id: "language-exchange",
      title: "Language Exchange",
      description: "Practice with a native speaker and help them learn too",
      difficulty: "Basics",
      duration: "20-30 min",
      category: "Educational",
      gradient: "from-rose-500 via-pink-600 to-purple-700",
      imageUrl: "/images/scenarios/language-exchange.jpg",
      skills: ["Cultural Exchange", "Teaching", "Mutual Learning"],
    },
  ];

  return scenarios;
};
